/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-variant": "#262626",
                "on-primary-fixed": "#000000",
                "error": "#ff6e84",
                "secondary-dim": "#db8ef0",
                "inverse-surface": "#fcf9f8",
                "primary-fixed": "#c782ff",
                "secondary-fixed-dim": "#efacff",
                "secondary-fixed": "#f4c0ff",
                "tertiary-fixed": "#ff9198",
                "on-error-container": "#ffb2b9",
                "on-primary-container": "#38005e",
                "surface-container-highest": "#262626",
                "error-dim": "#d73357",
                "on-background": "#ffffff",
                "surface-container-lowest": "#000000",
                "tertiary-dim": "#f47782",
                "on-tertiary-container": "#570014",
                "primary-container": "#c782ff",
                "on-secondary": "#5a1171",
                "error-container": "#a70138",
                "primary-fixed-dim": "#bd6efe",
                "surface-container": "#1a1a1a",
                "background": "#0e0e0e",
                "surface-container-low": "#131313",
                "tertiary-fixed-dim": "#fb7c87",
                "surface": "#0e0e0e",
                "secondary-container": "#6c2783",
                "primary-dim": "#c57eff",
                "on-surface-variant": "#adaaaa",
                "inverse-on-surface": "#565555",
                "on-error": "#490013",
                "on-secondary-container": "#f4beff",
                "secondary": "#ea9bff",
                "on-primary": "#490078",
                "outline-variant": "#484847",
                "tertiary": "#ff959c",
                "on-tertiary-fixed": "#39000a",
                "tertiary-container": "#fe7e89",
                "on-secondary-fixed": "#570d6e",
                "primary": "#d095ff",
                "on-tertiary": "#680a1e",
                "surface-dim": "#0e0e0e",
                "on-primary-fixed-variant": "#450073",
                "on-tertiary-fixed-variant": "#721324",
                "outline": "#767575",
                "surface-bright": "#2c2c2c",
                "surface-container-high": "#20201f",
                "on-surface": "#ffffff",
                "surface-tint": "#d095ff",
                "on-secondary-fixed-variant": "#77328d",
                "inverse-primary": "#8534c4"
            },
            fontFamily: {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
    plugins: [],
}